import { CategoryEntity, FamilyEntity, StatusTransferEntity, StockEntity } from "../stock";
import { SupplierEntity } from "../purchases";
import { CustomerEntity, SaleEntity } from "../sales";
import { EmployeeCreditEntity, EmployeeEntity, EmployeePaymentEntity, PuncheEntity } from "../hr";
import { BatchEntity, IngredientEntity } from "../production";
import { FenceEntity, MoneySourceEntity } from "../treasuries";
import { PurchaseEntity } from "../purchases/purchase.entity";
import { DistributionEntity } from "../distributions/distribution.entity";
import { PremiseEntity } from "../distributions";
import { QuantityCorrectionEntity } from '../stock/quantity-correction.entity';
export declare class UserEntity {
    id: number;
    code: string;
    name: string;
    password: string;
    notes: string;
    createdAt: Date;
    createdBy: number;
    lastUpdateAt: Date;
    lastUpdateBy: number;
    createdCategories: CategoryEntity[];
    updatedCategories: CategoryEntity[];
    createdPremises: PremiseEntity[];
    updatedPremises: PremiseEntity[];
    createdFamilies: FamilyEntity[];
    updatedFamilies: FamilyEntity[];
    createdSuppliers: SupplierEntity[];
    updatedSuppliers: SupplierEntity[];
    createdCustomers: CustomerEntity[];
    updatedCustomers: CustomerEntity[];
    createdEmployees: EmployeeEntity[];
    updatedEmployees: EmployeeEntity[];
    createdMoneySourceTransfers: MoneySourceEntity[];
    updatedMoneySourceTransfers: MoneySourceEntity[];
    createdStocks: StockEntity[];
    updatedStocks: StockEntity[];
    createdQuantityCorrections: QuantityCorrectionEntity[];
    updatedQuantityCorrections: QuantityCorrectionEntity[];
    createdIngredients: IngredientEntity[];
    updatedIngredients: IngredientEntity[];
    createdMoneySources: MoneySourceEntity[];
    updatedMoneySources: MoneySourceEntity[];
    createdPunches: PuncheEntity[];
    updatedPunches: PuncheEntity[];
    createdPurchases: PurchaseEntity[];
    updatedPurchases: PurchaseEntity[];
    createdSales: SaleEntity[];
    updatedSales: SaleEntity[];
    createdDistributions: DistributionEntity[];
    updatedDistributions: DistributionEntity[];
    createdBatches: BatchEntity[];
    updatedBatches: BatchEntity[];
    createdFences: FenceEntity[];
    updatedFences: FenceEntity[];
    createdStatusTransferStocks: StatusTransferEntity[];
    updatedStatusTransferStocks: StatusTransferEntity[];
    createdEmployeeCredits: EmployeeCreditEntity[];
    updatedEmployeeCredits: EmployeeCreditEntity[];
    createdEmployeePayments: EmployeePaymentEntity[];
    updatedEmployeePayments: EmployeePaymentEntity[];
}
